### ISSUE TITLE
COHD and Openpredict KPs are not returning query results

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/minihackathons#21] opened 2021-05-25 20:57 UTC
This issue to capture the results from the mini-hackathon that occurred on May 20. 
COHD and openpredict KPs were not returning results when Chris B ran the following query, possibly TRAPI validation errors

Here is the ARAX link for the results: https://arax.ncats.io/?source=ARS&id=62fa9f13-a7e4-4971-9580-1fb87d5345e2 
@CaseyTa, would you be able to take a look? Chris B and Anne would like to revisit these queries next week during the mini-hackathon on June 3.

------------------------------------------
qg = {
  "nodes": {
    "n0": {
      "categories": [
        "biolink:ChemicalSubstance"
      ],
      "name": "Chemical Substance"
    },
    "n1": {
      "name": "EGFR",
      "ids": ["NCBIGene:1956"]
    }
  },
  "edges": {
    "e0": {
      "subject": "n0",
      "object": "n1",
      "predicates": [
        "biolink:decreases_abundance_of",
        "biolink:decreases_activity_of",
        "biolink:decreases_expression_of",
        "biolink:decreases_synthesis_of",
        "biolink:increases_degradation_of",
        "biolink:disrupts",
        "biolink:negatively_regulates_entity_to_entity"
      ]
    }
  }
}

**Comment by CaseyTa** [comment] 2021-05-25 22:10
@tursynay, I think this is a duplicate of the standup meeting issue: https://github.com/NCATSTranslator/testing/issues/66

OpenPredict is not expected to return any results for this query. 

Here's a copy of my response in the other issue: 

> We had a similar finding as @balhoff for COHD. COHD is returning an error saying
>
>>    biolink:negatively_regulates_entity_to_entity was not recognized as a biolink predicate
>
>This is expected behavior, from my understanding of how errors should be handled.
>
>
> When I changed the query to biolink:entity_negatively_regulates_entity, COHD responds:
> 
> >    None of the predicates in ['biolink:decreases_abundance_of', 'biolink:decreases_activity_of',
>     'biolink:decreases_expression_of', 'biolink:decreases_synthesis_of', 'biolink:increases_degradation_of',
>     'biolink:disrupts', 'biolink:entity_negatively_regulates_entity'] are supported by COHD.
> 
> Again, this is expected behavior.

**Comment by tursynay** [comment] 2021-05-26 16:22
@CaseyTa , thank you for getting back. I will defer to @cbizon on the next steps for this issue.

**Closed** 2021-06-17 12:20 UTC
Labels: Warm-Up - EGFR, bug, demoscript
