### ISSUE TITLE
Scheduling around operation 

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/minihackathons#22] opened 2021-06-03 15:24 UTC
This issue is a reminder to follow up with Chris B and David K regarding: Discuss FDA status - Contained in RTX KG2. 
This will be discussed at the next Arch call. 

More details needed.

**Comment by vgardner-renci** [comment] 2021-06-17 16:56
Dupe of another issue

**Closed by vgardner-renci** 2021-06-17 16:56 UTC
Labels: demoscript
